## Использование Gamac на реальных данных
Описание реальных задач приведено в [документации](https://github.com/ITMO-CODE-AI/GaMAC/blob/develop/docs/CASE_RU.md)

### Импортируем нужные библиотеки

In [1]:
import os
import sys
sys.path.append('../../')

import numpy as np
import pandas as pd
from PIL import Image

from gamac.autoclustering import Gamac
from gamac.estimation.internal import Internal

### 1. Данные промышленных логов (семпл)
Кластеризация логов направлена на автоматическое выделение групп записей, связанных с общими источниками событий, такими как прикладные процессы, системные события или среды исполнения. Основная цель — обнаружить скрытые паттерны в данных, которые позволяют косвенно определить природу возникновения логов, даже если их формат не содержит явных указаний на источник.

Для получения данных нужно выгрузить их из Minio, данные лежат в: datasets/data/synthetic_logs_1kk.csv

И переложить из корня в папку data/

Примечание: выполнение по этому датасету проходит очень долгое время в связи с его объемом

In [2]:
!pip install minio

Requirement already satisfied: minio in /.venv/lib/python3.12/site-packages (7.2.18)
Requirement already satisfied: argon2-cffi in /.venv/lib/python3.12/site-packages (from minio) (25.1.0)
Requirement already satisfied: certifi in /.venv/lib/python3.12/site-packages (from minio) (2025.10.5)
Requirement already satisfied: pycryptodome in /.venv/lib/python3.12/site-packages (from minio) (3.23.0)
Requirement already satisfied: typing-extensions in /.venv/lib/python3.12/site-packages (from minio) (4.15.0)
Requirement already satisfied: urllib3 in /.venv/lib/python3.12/site-packages (from minio) (2.5.0)
Requirement already satisfied: argon2-cffi-bindings in /.venv/lib/python3.12/site-packages (from argon2-cffi->minio) (25.1.0)
Requirement already satisfied: cffi>=1.0.1 in /.venv/lib/python3.12/site-packages (from argon2-cffi-bindings->argon2-cffi->minio) (2.0.0)
Requirement already satisfied: pycparser in /.venv/lib/python3.12/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->minio) (2.23)

In [3]:
# загрзука данных из MinIO
import os
from minio import Minio
os.environ["SSL_CERT_FILE"] = 'all-data/public.crt'

In [4]:
def download_data_without_creds(data):
    client = Minio(
    '94.124.179.195:9000',
    secure=True
    )
    data = client.fget_object(
        'datasets',
        f'data/{data}',
        f'all-data/{data}'
    )

In [5]:
download_data_without_creds('synthetic_logs_1kk.csv')

In [6]:
# Импортируем датафрейм
data = pd.read_csv('all-data/synthetic_logs_1kk.csv', na_values=['missing'])
data['timestamp'] = pd.to_datetime(data['timestamp'], errors='coerce')

In [7]:
data.head(5)

,Unnamed: 0,object,agent,subject,environment,source,result,result code,tag,log level,label,traceback,protocol,action,property,timestamp
0,0,NaN,NaN,thread,NaN,24.149.203.18,[<:subject:> <:source:>] File does not exist:<...,NaN,NaN,error,NaN,event interval expired,NaN,NaN,lifetime 05:00,2025-04-18 10:08:58
1,1,dfs.FSNamesystem,ocsp.digicert.com:80,out block blk 8855628190418004805,NaN,transfer block blk -1132082380757283113 to 10....,<:action:>* NameSystem.addStoredBlock: blockMa...,NaN,27052.0,WARN,NaN,Redundant addStoredBlock request received for ...,NaN,Access denied,power/control problem,2025-03-28 10:08:58
2,2,spoolsv.exe *64,news.17173.com:80,thread,NaN,transfer block blk -1009207079038502874 to 10....,link errors remain current,NaN,6708.0,-1,state_change.unavailable,Redundant addStoredBlock request received for ...,NaN,NaN,power/control problem,2025-04-19 10:08:58
3,3,chrome.exe,pubads.g.doubleclick.net:443,node-139,NaN,84.92.64.33,"<:action:>, <:NUM:> bytes <:*:> <:*:> sent, <:...",NaN,NaN,NaN,NaN,timed,NaN,close,power/control problem,2025-04-14 10:08:58
4,4,partition,mini.cpc.sogou.com:80,thread,NaN,85.64.10.104,critical,NaN,385417.0,-1,status,must start with /,NaN,NaN,power/control problem,2025-04-16 10:08:58

In [8]:
gamac = Gamac(iter_limit=100, target_measures={Internal.BR})

result = gamac.run(table=data)

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.71G [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/316 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/905 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/389 [00:00<?, ?B/s]

/.venv/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

=== MEASURES 1.1026804447174072s, {'BR': -16.44806543893915} ===
=== MEASURES 0.01060795783996582s, {'BR': -12.456415287817997} ===
=== ALGO 3.031867265701294s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 7, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== ALGO 1.9073486328125e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.1416808612149756, 'max_iter': 5, 'tol': 0.0001} ===
=== ALGO 41.14652729034424s, FailedRun, {'name': 'DBSCAN', 'eps': 1.4608874205047306, 'eps_sq': 2.1341920553889655, 'min_samples': 12} ===
=== ALGO 22.90702772140503s, FailedRun, {'name': 'HDBSCAN', 'min_cluster_size': 9, 'min_samples': 7} ===
=== MEASURES 0.008957147598266602s, {'BR': -11.895881968258244} ===
=== ALGO 224.63210582733154s, SuccessRun, {'name': 'Birch', 'threshold': 0.7799884730999638, 'branching_factor': 45, 'n_clusters': 9} ===
=== MEASURES 0.008044719696044922s, {'BR': -11.790844441260644} ===
=== ALGO 0.07422828674316406s, SuccessRun, {'name': 'KMeans', 'n_clusters': 8, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.024184703826904297s, {'BR': -10.787097118026137} ===
=== ALGO 1.8875977993011475s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 13, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== ALGO 2.0742416381835938e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.32906111330045973, 'max_iter': 5, 'tol': 0.0001} ===
=== ALGO 34.55871081352234s, FailedRun, {'name': 'DBSCAN', 'eps': 0.3282081481904741, 'eps_sq': 0.10772058853862021, 'min_samples': 5} ===
=== ALGO 161.11112642288208s, FailedRun, {'name': 'HDBSCAN', 'min_cluster_size': 9, 'min_samples': 15} ===
=== MEASURES 0.032035112380981445s, {'BR': -12.5287985831959} ===
=== ALGO 305.36749267578125s, SuccessRun, {'name': 'Birch', 'threshold': 0.40380122016346376, 'branching_factor': 66, 'n_clusters': 7} ===
=== MEASURES 0.026360511779785156s, {'BR': -14.626955715340738} ===
=== ALGO 0.10812187194824219s, SuccessRun, {'name': 'KMeans', 'n_clusters': 2, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.0062906742095947266s, {'BR': -12.72857851941152} ===
=== ALGO 0.30052900314331055s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 5, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== ALGO 1.33514404296875e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.424516620793546, 'max_iter': 5, 'tol': 0.0001} ===
=== ALGO 35.00493264198303s, FailedRun, {'name': 'DBSCAN', 'eps': 0.5996878854593198, 'eps_sq': 0.3596255599666703, 'min_samples': 8} ===
=== ALGO 147.67333221435547s, FailedRun, {'name': 'HDBSCAN', 'min_cluster_size': 7, 'min_samples': 14} ===
=== MEASURES 0.0377657413482666s, {'BR': -12.796830614679832} ===
=== ALGO 189.10152435302734s, SuccessRun, {'name': 'Birch', 'threshold': 0.6134747101865068, 'branching_factor': 36, 'n_clusters': 6} ===
=== MEASURES 0.03256654739379883s, {'BR': -14.626955715340738} ===
=== ALGO 0.10866475105285645s, SuccessRun, {'name': 'KMeans', 'n_clusters': 2, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.011214494705200195s, {'BR': -10.603696234549638} ===
=== ALGO 1.6172020435333252s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 14, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.0057904720306396484s, {'BR': -13.63555887892942} ===
=== ALGO 0.06407451629638672s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 3, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.011880159378051758s, {'BR': -10.043751737432197} ===
=== ALGO 0.12092733383178711s, SuccessRun, {'name': 'KMeans', 'n_clusters': 15, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.009576082229614258s, {'BR': -11.733359686832364} ===
=== ALGO 0.5421864986419678s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 9, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.010333776473999023s, {'BR': -11.268422670158856} ===
=== ALGO 0.6654677391052246s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 10, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.012895345687866211s, {'BR': -12.439184749892688} ===
=== ALGO 0.3139913082122803s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 7, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.013094425201416016s, {'BR': -10.415551561404795} ===
=== ALGO 0.1312417984008789s, SuccessRun, {'name': 'KMeans', 'n_clusters': 14, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.012372970581054688s, {'BR': -10.519445390328126} ===
=== ALGO 0.11848664283752441s, SuccessRun, {'name': 'KMeans', 'n_clusters': 12, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.011652231216430664s, {'BR': -10.628205450125984} ===
=== ALGO 0.11418533325195312s, SuccessRun, {'name': 'KMeans', 'n_clusters': 12, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.009880304336547852s, {'BR': -12.004987349040043} ===
=== ALGO 0.07958984375s, SuccessRun, {'name': 'KMeans', 'n_clusters': 7, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.007355213165283203s, {'BR': -14.4973732384582} ===
=== ALGO 0.03910470008850098s, SuccessRun, {'name': 'KMeans', 'n_clusters': 3, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.0073032379150390625s, {'BR': -13.63555887892942} ===
=== ALGO 0.06987619400024414s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 3, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.007843494415283203s, {'BR': -13.137139840028079} ===
=== ALGO 0.1211252212524414s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 4, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.008662939071655273s, {'BR': -13.137139840028079} ===
=== ALGO 0.11542749404907227s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 4, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.021960973739624023s, {'BR': -10.273616493579778} ===
=== ALGO 0.14763545989990234s, SuccessRun, {'name': 'KMeans', 'n_clusters': 14, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.014887571334838867s, {'BR': -10.333073995054082} ===
=== ALGO 0.1525564193725586s, SuccessRun, {'name': 'KMeans', 'n_clusters': 15, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.010989665985107422s, {'BR': -11.005128642000962} ===
=== ALGO 0.10679316520690918s, SuccessRun, {'name': 'KMeans', 'n_clusters': 10, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.03735685348510742s, {'BR': -10.588381659240046} ===
=== ALGO 0.14750218391418457s, SuccessRun, {'name': 'KMeans', 'n_clusters': 12, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== ALGO 21.271512031555176s, FailedRun, {'name': 'HDBSCAN', 'min_cluster_size': 15, 'min_samples': 8} ===
=== MEASURES 0.01687479019165039s, {'BR': -10.81657286632356} ===
=== ALGO 1.5114798545837402s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 13, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.01519632339477539s, {'BR': -11.152108140799085} ===
=== ALGO 0.12417006492614746s, SuccessRun, {'name': 'KMeans', 'n_clusters': 10, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== ALGO 40.622793436050415s, FailedRun, {'name': 'DBSCAN', 'eps': 1.30948277694347, 'eps_sq': 1.7147451431115817, 'min_samples': 6} ===
=== MEASURES 0.017727375030517578s, {'BR': -11.116178636234803} ===
=== ALGO 1.0161323547363281s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 11, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.012019872665405273s, {'BR': -13.68084563328776} ===
=== ALGO 0.0708470344543457s, SuccessRun, {'name': 'KMeans', 'n_clusters': 3, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== ALGO 34.244195222854614s, FailedRun, {'name': 'DBSCAN', 'eps': 0.5577063725779295, 'eps_sq': 0.3110363980140324, 'min_samples': 14} ===
=== MEASURES 0.005248069763183594s, {'BR': -13.63555887892942} ===
=== ALGO 0.28586459159851074s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 3, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.009091854095458984s, {'BR': -11.333796106817859} ===
=== ALGO 0.0835573673248291s, SuccessRun, {'name': 'KMeans', 'n_clusters': 9, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.010894298553466797s, {'BR': -10.226723589653911} ===
=== ALGO 0.11546015739440918s, SuccessRun, {'name': 'KMeans', 'n_clusters': 14, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== ALGO 108.31240963935852s, FailedRun, {'name': 'HDBSCAN', 'min_cluster_size': 8, 'min_samples': 10} ===
=== MEASURES 0.017095327377319336s, {'BR': -11.834312659529907} ===
=== ALGO 0.9456374645233154s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 9, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.01967167854309082s, {'BR': -10.638428363359214} ===
=== ALGO 1.4148128032684326s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 13, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.01837754249572754s, {'BR': -10.836763017744753} ===
=== ALGO 1.57499361038208s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 13, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.012855052947998047s, {'BR': -12.850044840651718} ===
=== ALGO 0.29264020919799805s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 6, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.01195669174194336s, {'BR': -12.628230574491893} ===
=== ALGO 0.2976067066192627s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 6, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.009861230850219727s, {'BR': -13.70166978149816} ===
=== ALGO 0.060884714126586914s, SuccessRun, {'name': 'KMeans', 'n_clusters': 3, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.014342784881591797s, {'BR': -11.030057537543657} ===
=== ALGO 0.12549161911010742s, SuccessRun, {'name': 'KMeans', 'n_clusters': 11, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.010025978088378906s, {'BR': -13.021199496443677} ===
=== ALGO 0.07410597801208496s, SuccessRun, {'name': 'KMeans', 'n_clusters': 4, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.014208316802978516s, {'BR': -10.742674150527312} ===
=== ALGO 1.0910141468048096s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 12, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.012598514556884766s, {'BR': -11.018724553034485} ===
=== ALGO 0.10950851440429688s, SuccessRun, {'name': 'KMeans', 'n_clusters': 10, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.013729333877563477s, {'BR': -10.887950137610307} ===
=== ALGO 0.12459969520568848s, SuccessRun, {'name': 'KMeans', 'n_clusters': 11, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.01453852653503418s, {'BR': -10.631436204645032} ===
=== ALGO 0.13481831550598145s, SuccessRun, {'name': 'KMeans', 'n_clusters': 13, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.0117950439453125s, {'BR': -11.924012219876898} ===
=== ALGO 0.47795820236206055s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 8, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.01309061050415039s, {'BR': -11.203902117234552} ===
=== ALGO 0.11119914054870605s, SuccessRun, {'name': 'KMeans', 'n_clusters': 10, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.01423954963684082s, {'BR': -10.602370343940223} ===
=== ALGO 0.13000154495239258s, SuccessRun, {'name': 'KMeans', 'n_clusters': 12, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.009257316589355469s, {'BR': -13.020830336820632} ===
=== ALGO 0.06387639045715332s, SuccessRun, {'name': 'KMeans', 'n_clusters': 4, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.008813858032226562s, {'BR': -14.626955715340738} ===
=== ALGO 0.03862261772155762s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 2, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.014816999435424805s, {'BR': -10.178284077976082} ===
=== ALGO 0.14502573013305664s, SuccessRun, {'name': 'KMeans', 'n_clusters': 14, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.00882411003112793s, {'BR': -13.54890192781817} ===
=== ALGO 0.06151270866394043s, SuccessRun, {'name': 'KMeans', 'n_clusters': 4, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.012121438980102539s, {'BR': -11.271006748293033} ===
=== ALGO 0.7015347480773926s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 10, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.01199793815612793s, {'BR': -11.226520530343555} ===
=== ALGO 0.6683125495910645s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 10, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== ALGO 1.3113021850585938e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.7072815321298531, 'max_iter': 5, 'tol': 0.0001} ===
=== MEASURES 0.014370441436767578s, {'BR': -10.288300404967835} ===
=== ALGO 0.13767194747924805s, SuccessRun, {'name': 'KMeans', 'n_clusters': 14, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.014119863510131836s, {'BR': -11.342787084289258} ===
=== ALGO 0.9448285102844238s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 11, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.01434016227722168s, {'BR': -10.771599043959139} ===
=== ALGO 0.1275484561920166s, SuccessRun, {'name': 'KMeans', 'n_clusters': 11, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.014928817749023438s, {'BR': -10.675731187704546} ===
=== ALGO 0.1362619400024414s, SuccessRun, {'name': 'KMeans', 'n_clusters': 12, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.015684843063354492s, {'BR': -10.264166925634301} ===
=== ALGO 0.14637494087219238s, SuccessRun, {'name': 'KMeans', 'n_clusters': 14, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.015680789947509766s, {'BR': -10.517156584066162} ===
=== ALGO 0.15067839622497559s, SuccessRun, {'name': 'KMeans', 'n_clusters': 14, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.03010702133178711s, {'BR': -13.776286790030744} ===
=== ALGO 223.36708402633667s, SuccessRun, {'name': 'Birch', 'threshold': 0.5656886191405656, 'branching_factor': 46, 'n_clusters': 4} ===
=== ALGO 42.69680309295654s, FailedRun, {'name': 'DBSCAN', 'eps': 1.2519936652496895, 'eps_sq': 1.5674881378253516, 'min_samples': 9} ===
=== MEASURES 0.01647186279296875s, {'BR': -12.23948019731142} ===
=== ALGO 0.4739985466003418s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 6, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.02115654945373535s, {'BR': -10.653020133695913} ===
=== ALGO 0.1836094856262207s, SuccessRun, {'name': 'KMeans', 'n_clusters': 14, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.01584625244140625s, {'BR': -11.10823376371999} ===
=== ALGO 0.1491858959197998s, SuccessRun, {'name': 'KMeans', 'n_clusters': 10, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.031694889068603516s, {'BR': -12.72857851941152} ===
=== ALGO 0.24224472045898438s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 5, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.00969696044921875s, {'BR': -13.711310231352174} ===
=== ALGO 0.06052827835083008s, SuccessRun, {'name': 'KMeans', 'n_clusters': 3, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.021569013595581055s, {'BR': -13.137139840028079} ===
=== ALGO 0.16256499290466309s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 4, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.015537023544311523s, {'BR': -10.241475910700252} ===
=== ALGO 0.15230870246887207s, SuccessRun, {'name': 'KMeans', 'n_clusters': 15, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.014949798583984375s, {'BR': -10.163256443557746} ===
=== ALGO 0.14669275283813477s, SuccessRun, {'name': 'KMeans', 'n_clusters': 14, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.010367631912231445s, {'BR': -12.72857851941152} ===
=== ALGO 0.19544315338134766s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 5, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.012716054916381836s, {'BR': -11.042513895248046} ===
=== ALGO 0.1142737865447998s, SuccessRun, {'name': 'KMeans', 'n_clusters': 10, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.012786388397216797s, {'BR': -11.002502809548984} ===
=== ALGO 0.11585068702697754s, SuccessRun, {'name': 'KMeans', 'n_clusters': 10, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.013702869415283203s, {'BR': -10.930679025236186} ===
=== ALGO 1.0633018016815186s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 12, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.011319398880004883s, {'BR': -12.461520357146833} ===
=== ALGO 0.420795202255249s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 8, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.008801937103271484s, {'BR': -13.519009640791682} ===
=== ALGO 0.06212449073791504s, SuccessRun, {'name': 'KMeans', 'n_clusters': 4, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.009420394897460938s, {'BR': -12.504698182981247} ===
=== ALGO 0.07018423080444336s, SuccessRun, {'name': 'KMeans', 'n_clusters': 5, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== ALGO 1.2874603271484375e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.9973494952224703, 'max_iter': 5, 'tol': 0.0001} ===
=== MEASURES 0.009414911270141602s, {'BR': -12.339828142231044} ===
=== ALGO 0.20238041877746582s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 5, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.011208057403564453s, {'BR': -12.246902150014575} ===
=== ALGO 0.5650887489318848s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 9, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.011965036392211914s, {'BR': -11.262350733386546} ===
=== ALGO 0.09901857376098633s, SuccessRun, {'name': 'KMeans', 'n_clusters': 9, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.017199277877807617s, {'BR': -10.589319670959616} ===
=== ALGO 1.523517370223999s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 14, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.016860008239746094s, {'BR': -10.4349628472284} ===
=== ALGO 0.15343093872070312s, SuccessRun, {'name': 'KMeans', 'n_clusters': 14, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.042357444763183594s, {'BR': -11.266806052756417} ===
=== ALGO 176.79467940330505s, SuccessRun, {'name': 'Birch', 'threshold': 0.4333429397922487, 'branching_factor': 34, 'n_clusters': 15} ===
=== ALGO 1.6927719116210938e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.8057801910787914, 'max_iter': 5, 'tol': 0.0001} ===

In [9]:
# Получение топ-50 меток по лучшему классификатору
print(result.labels[:50])

[ 0  8 14 12 14  8  3  6 12  5 13 14  7  1  5  5 14  5  5 12  6  1 10  5
 11  8  3 12  0  5  6  1 10 11  5  1 14  8  5 14  5  2  5 11 14  1  5 14
  3  5]

### 2. Данные по анализу цветов RGB-изображений
Кластеризация цветов RGB-изображений направлена на автоматическое группирование пикселей со схожими цветовыми значениями в отдельные кластеры, где каждый кластер представляет собой усреднённый цвет или доминирующий оттенок из соответствующей группы. Основная цель — упростить представление изображения за счёт выделения ключевых цветовых паттернов, что может быть полезно для задач сжатия данных, сегментации объектов, снижения шума или анализа цветовой палитры.

In [10]:
# Импортируем картинки
images = []

# Получаем список файлов в директории
for filename in os.listdir('../../data/images/'):
    if 'png' not in filename:
        continue
    file_path = os.path.join('../../data/images/', filename)

    # Пытаемся открыть файл как изображение
    with Image.open(file_path) as img:
        images.append(img.copy())

images[:5]

[<PIL.Image.Image image mode=RGBA size=600x600>,
 <PIL.Image.Image image mode=RGBA size=651x888>,
 <PIL.Image.Image image mode=RGBA size=3433x4606>,
 <PIL.Image.Image image mode=RGBA size=114x102>,
 <PIL.Image.Image image mode=RGBA size=744x1052>]

### Запустим подбор

In [11]:
# Для кластеризации передадим константный пустой текст
gamac = Gamac(iter_limit=30)
empty_texts = ['' for i in range(len(images))]

result = gamac.run(image=images, text=empty_texts)

/.venv/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

=== Started CVI prediction ===
=== CVI prediction iteration 1/2 ====
=== CVI prediction iteration 2/2 ====
=== Picked SYM in 12.066900968551636s ===
=== MEASURES 0.3256947994232178s, {'SYM': 0.0004269955482819506} ===
=== MEASURES 0.050510406494140625s, {'SYM': 0.007340950293377901} ===
=== ALGO 1.6903407573699951s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 4, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== ALGO 1.9311904907226562e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.15436615777741444, 'max_iter': 5, 'tol': 0.0001} ===
=== MEASURES 0.12204813957214355s, {'SYM': 0.0} ===
=== ALGO 0.794041633605957s, SuccessRun, {'name': 'DBSCAN', 'eps': 1.2320443188029702, 'eps_sq': 1.5179332034946749, 'min_samples': 5} ===
=== ALGO 0.7455964088439941s, FailedRun, {'name': 'HDBSCAN', 'min_cluster_size': 5, 'min_samples': 7} ===
=== ALGO 3.2698981761932373s, FailedRun, {'name': 'Birch', 'threshold': 0.27648330189043835, 'branching_factor': 70, 'n_clusters': 14} ===
=== MEASURES 0.23574066162109375s, {'SYM': 0.00864739212826399} ===
=== ALGO 0.2533843517303467s, SuccessRun, {'name': 'KMeans', 'n_clusters': 3, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.03893160820007324s, {'SYM': 0.015195770392852614} ===
=== ALGO 0.2711036205291748s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 7, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== ALGO 1.4543533325195312e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.9412078217640831, 'max_iter': 5, 'tol': 0.0001} ===
=== MEASURES 0.08506584167480469s, {'SYM': 0.0} ===
=== ALGO 0.6868162155151367s, SuccessRun, {'name': 'DBSCAN', 'eps': 1.3589948138638621, 'eps_sq': 1.8468669041088732, 'min_samples': 9} ===
=== ALGO 0.1844480037689209s, FailedRun, {'name': 'HDBSCAN', 'min_cluster_size': 12, 'min_samples': 6} ===
=== MEASURES 0.06849384307861328s, {'SYM': 0.004833434304005482} ===
=== ALGO 1.334282636642456s, SuccessRun, {'name': 'Birch', 'threshold': 0.11501959722046787, 'branching_factor': 22, 'n_clusters': 3} ===
=== ALGO 0.05888676643371582s, FailedRun, {'name': 'KMeans', 'n_clusters': 14, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.03925013542175293s, {'SYM': 0.02759074529707466} ===
=== ALGO 0.6276199817657471s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 10, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== ALGO 1.5020370483398438e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.13479696246046755, 'max_iter': 5, 'tol': 0.0001} ===
=== ALGO 0.2675502300262451s, FailedRun, {'name': 'DBSCAN', 'eps': 0.3547677836818506, 'eps_sq': 0.12586018033853233, 'min_samples': 12} ===
=== ALGO 1.3893969058990479s, FailedRun, {'name': 'HDBSCAN', 'min_cluster_size': 11, 'min_samples': 15} ===
=== MEASURES 0.217393159866333s, {'SYM': 0.019568614443044505} ===
=== ALGO 2.4175713062286377s, SuccessRun, {'name': 'Birch', 'threshold': 0.5813174876176639, 'branching_factor': 45, 'n_clusters': 5} ===
=== ALGO 0.07674527168273926s, FailedRun, {'name': 'KMeans', 'n_clusters': 15, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== ALGO 0.6001381874084473s, FailedRun, {'name': 'BisectingKMeans', 'n_clusters': 12, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.07065582275390625s, {'SYM': 0.013840276905994391} ===
=== ALGO 0.1173548698425293s, SuccessRun, {'name': 'KMeans', 'n_clusters': 6, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== ALGO 0.07130146026611328s, FailedRun, {'name': 'KMeans', 'n_clusters': 14, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== ALGO 0.25772714614868164s, FailedRun, {'name': 'DBSCAN', 'eps': 0.22426317905246543, 'eps_sq': 0.05029397347871817, 'min_samples': 12} ===
=== MEASURES 0.09968447685241699s, {'SYM': 0.0050148854740091125} ===
=== ALGO 0.11873078346252441s, SuccessRun, {'name': 'KMeans', 'n_clusters': 3, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.039893388748168945s, {'SYM': 0.03983120278748802} ===
=== ALGO 0.5344574451446533s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 11, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.03843069076538086s, {'SYM': 0.04020050903423363} ===
=== ALGO 0.507270097732544s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 11, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.06738400459289551s, {'SYM': 0.008243241735125771} ===
=== ALGO 0.09090256690979004s, SuccessRun, {'name': 'KMeans', 'n_clusters': 4, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.049668312072753906s, {'SYM': 0.029243019037261293} ===
=== ALGO 0.08483338356018066s, SuccessRun, {'name': 'KMeans', 'n_clusters': 8, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.03788280487060547s, {'SYM': 0.03614673962913185} ===
=== ALGO 0.10019230842590332s, SuccessRun, {'name': 'KMeans', 'n_clusters': 10, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.07512640953063965s, {'SYM': 0.0069442283695535624} ===
=== ALGO 0.09039044380187988s, SuccessRun, {'name': 'KMeans', 'n_clusters': 3, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== ALGO 1.4066696166992188e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.9297302694012719, 'max_iter': 5, 'tol': 0.0001} ===

In [12]:
# Метки по датасету
print(result.labels)

[ 8 10  8  3  6  1  5  4  4  8  4  4 10 10  5  3  4  9  1  3  8  8  3  1
  8  4  4  8  8  5  8  8  7 10  6  3  5  3  9  6  4  1  2  7 10  9  7  1
  1  7  3  9  9 10  4  8  8  6  5  2 10  1  2  3  2  7  4  6  4  1 10  2
  9  5  2  9  6  8  4  5  1  9  4  4  3 10  5  5  4  2  3  3  2  4  4 10
  5  5  9  8  4  7  1  8  8  1  5  8  4 10  4  8  5  3  4  3  1  4  5  4
  2  2  9  3  8  1  4  2  5  9  8  8  6  3 10  3 10  7 10  8  1  1  2 10
  8  5 10  6  4  5  1  3  9  7  6  7  5  5  4  3  4  4  3  4  9  9  3  4
  8  8  8  2  5 10  9 10  1  2  2  6  8  7  3  9  2  5  1  4  5  7 10  6
  4  6  3  2  5  1  6  4  6  7  3  1  1  9 10  8  4  2  4  6  9  4  4  7
  8  4  1  4  6  9  6  5  4  6  3  4  7 10  8  9  3  2  9 10 10  5  6  4
  4  4  5 10  4  4  9  8  3  7  5  5 10  3  2 10  6  0  2  5  5  2  4  5
  9  6  4  4 10 10  3  3  4 10  1  9 10  5  8  9  2 10 10  9  2  8  8 10
  5  8  6  2  9  2  5  1  5  5  4  9  4  2  7  4  8  6 10 10  1  9 10  6
  8  0  5  1  6  4  6  8  2  5  2 10  8  3  3 10  2  6  8  2  2  6  5  9
  7 10  6  3  2  9  1  2  9  2  8  9  5  4  6  2  5  2  7  9  9  3  4  2
  8  4  9  3  4 10  2  5  7  1  8  6  8  1  3  9 10  5  9  2  0  6  3 10
  4  6  5  6  6 10  8  2  4  3  1  8  4  4  4  9  3  8  5  8  2  8  4  6
  6  1  9  1  5  8  1  4  6 10  4  6  4  9  1 10  8  2  1  9  4  8 10  2
  9  4  9  7  6  6  4 10  9  7  9  2  7  6 10  5  5 10  1 10  8  6  8  2
  2  5  4  1  4  7  2  4  4  4  1  7  8  8  1  7  4  7  4  2  2  5  6  8
  8  4  2  2  4  4  4  4  6  6  5  8  3  6  2  1  4  5 10  1  8]

### Аналогичные действия с GaMAC, установленным через pip

In [1]:
!pip install -U --extra-index-url https://test.pypi.org/simple/ Gamac --extra-index-url https://download.pytorch.org/whl/cu128

Looking in indexes: https://pypi.org/simple, https://test.pypi.org/simple/, https://download.pytorch.org/whl/cu128
Collecting Gamac
  Downloading https://test-files.pythonhosted.org/packages/f3/64/a985e1bc2128e9a71035bba0a1a936c6bbe96d93647ecb61d596774edfe1/gamac-1.0.2-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: accelerate==0.33.0 in /.venv/lib/python3.12/site-packages (from Gamac) (0.33.0)
Requirement already satisfied: datasets==3.6.0 in /.venv/lib/python3.12/site-packages (from Gamac) (3.6.0)
Requirement already satisfied: cuda-bindings==12.8.0 in /.venv/lib/python3.12/site-packages (from Gamac) (12.8.0)
Requirement already satisfied: cuda-python==12.8.0 in /.venv/lib/python3.12/site-packages (from Gamac) (12.8.0)
Requirement already satisfied: cupy-cuda12x==13.3.0 in /.venv/lib/python3.12/site-packages (from Gamac) (13.3.0)
Requirement already satisfied: cuvs-cu12==25.2.1 in /.venv/lib/python3.12/site-packages (from Gamac) (25.2.1)
Requirement already satisfied: distributed==2024.12.1 in /.venv/lib/python3.12/site-packages (from Gamac) (2024.12.1)
Requirement already satisfied: distributed-ucxx-cu12==0.42.0 in /.venv/lib/python3.12/site-packages (from Gamac) (0.42.0)
Requirement already satisfied: huggingface-hub==0.24.6 in /.venv/lib/python3.12/site-packages (from Gamac) (0.24.6)
Requirement already satisfied: Jinja2==3.1.4 in /.venv/lib/python3.12/site-packages (from Gamac) (3.1.4)
Requirement already satisfied: joblib==1.4.2 in /.venv/lib/python3.12/site-packages (from Gamac) (1.4.2)
Requirement already satisfied: libcuvs-cu12==25.2.1 in /.venv/lib/python3.12/site-packages (from Gamac) (25.2.1)
Requirement already satisfied: libraft-cu12==25.2.0 in /.venv/lib/python3.12/site-packages (from Gamac) (25.2.0)
Requirement already satisfied: libucx-cu12==1.18.1 in /.venv/lib/python3.12/site-packages (from Gamac) (1.18.1)
Requirement already satisfied: libucxx-cu12==0.42.0 in /.venv/lib/python3.12/site-packages (from Gamac) (0.42.0)
Requirement already satisfied: llvmlite==0.43.0 in /.venv/lib/python3.12/site-packages (from Gamac) (0.43.0)
Requirement already satisfied: matplotlib==3.9.2 in /.venv/lib/python3.12/site-packages (from Gamac) (3.9.2)
Requirement already satisfied: matplotlib-inline==0.1.7 in /.venv/lib/python3.12/site-packages (from Gamac) (0.1.7)
Requirement already satisfied: numba==0.60.0 in /.venv/lib/python3.12/site-packages (from Gamac) (0.60.0)
Requirement already satisfied: numpy==1.26.4 in /.venv/lib/python3.12/site-packages (from Gamac) (1.26.4)
Requirement already satisfied: nvidia-cublas-cu12==12.8.3.14 in /.venv/lib/python3.12/site-packages (from Gamac) (12.8.3.14)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.57 in /.venv/lib/python3.12/site-packages (from Gamac) (12.8.57)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.61 in /.venv/lib/python3.12/site-packages (from Gamac) (12.8.61)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.57 in /.venv/lib/python3.12/site-packages (from Gamac) (12.8.57)
Requirement already satisfied: nvidia-cudnn-cu12==9.7.1.26 in /.venv/lib/python3.12/site-packages (from Gamac) (9.7.1.26)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.41 in /.venv/lib/python3.12/site-packages (from Gamac) (11.3.3.41)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.55 in /.venv/lib/python3.12/site-packages (from Gamac) (10.3.9.55)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.2.55 in /.venv/lib/python3.12/site-packages (from Gamac) (11.7.2.55)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.7.53 in /.venv/lib/python3.12/site-packages (from Gamac) (12.5.7.53)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.3 in /.venv/lib/python3.12/site-packages (from Gamac) (0.6.3)
Requirement already satisfied: nvidia-ml-py==12.570.86 in /.venv/lib/python3.12/site-packages (from Gamac) (12.570.86)
Requirement already satisfied: nvidia-nccl-cu12==2.26.2 in /.venv/lib/python3.12/site-packages (from Gamac) (2.26.2)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.61 in /.venv/lib/python3.12/site-packages (from Gamac) (12.8.61)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.55 in /.venv/lib/python3.12/site-packages (from Gamac) (12.8.55)
Requirement already satisfied: optuna==4.3.0 in /.venv/lib/python3.12/site-packages (from Gamac) (4.3.0)
Requirement already satisfied: packaging==24.1 in /.venv/lib/python3.12/site-packages (from Gamac) (24.1)
Requirement already satisfied: pillow==10.4.0 in /.venv/lib/python3.12/site-packages (from Gamac) (10.4.0)
Requirement already satisfied: pyarrow==17.0.0 in /.venv/lib/python3.12/site-packages (from Gamac) (17.0.0)
Requirement already satisfied: pytest>=8.3.5 in /.venv/lib/python3.12/site-packages (from Gamac) (8.4.2)
Requirement already satisfied: safetensors==0.4.4 in /.venv/lib/python3.12/site-packages (from Gamac) (0.4.4)
Requirement already satisfied: scikit-learn==1.5.1 in /.venv/lib/python3.12/site-packages (from Gamac) (1.5.1)
Requirement already satisfied: scipy==1.14.1 in /.venv/lib/python3.12/site-packages (from Gamac) (1.14.1)
Requirement already satisfied: SQLAlchemy==2.0.40 in /.venv/lib/python3.12/site-packages (from Gamac) (2.0.40)
Requirement already satisfied: sympy==1.13.3 in /.venv/lib/python3.12/site-packages (from Gamac) (1.13.3)
Requirement already satisfied: tokenizers==0.19.1 in /.venv/lib/python3.12/site-packages (from Gamac) (0.19.1)
Requirement already satisfied: torch==2.7.0+cu128 in /.venv/lib/python3.12/site-packages (from Gamac) (2.7.0+cu128)
Requirement already satisfied: torchaudio==2.7.0 in /.venv/lib/python3.12/site-packages (from Gamac) (2.7.0+cu128)
Requirement already satisfied: torchvision==0.22.0 in /.venv/lib/python3.12/site-packages (from Gamac) (0.22.0+cu128)
Requirement already satisfied: tqdm==4.66.5 in /.venv/lib/python3.12/site-packages (from Gamac) (4.66.5)
Requirement already satisfied: umap-learn==0.5.7 in /.venv/lib/python3.12/site-packages (from Gamac) (0.5.7)
Requirement already satisfied: transformers==4.44.2 in /.venv/lib/python3.12/site-packages (from Gamac) (4.44.2)
Requirement already satisfied: wheel==0.45.1 in /.venv/lib/python3.12/site-packages (from Gamac) (0.45.1)
Requirement already satisfied: xgboost==3.0.0 in /.venv/lib/python3.12/site-packages (from Gamac) (3.0.0)
Requirement already satisfied: psutil in /.venv/lib/python3.12/site-packages (from accelerate==0.33.0->Gamac) (7.1.0)
Requirement already satisfied: pyyaml in /.venv/lib/python3.12/site-packages (from accelerate==0.33.0->Gamac) (6.0.3)
Requirement already satisfied: fastrlock>=0.5 in /.venv/lib/python3.12/site-packages (from cupy-cuda12x==13.3.0->Gamac) (0.8.3)
Requirement already satisfied: pylibraft-cu12==25.2.* in /.venv/lib/python3.12/site-packages (from cuvs-cu12==25.2.1->Gamac) (25.2.0)
Requirement already satisfied: filelock in /.venv/lib/python3.12/site-packages (from datasets==3.6.0->Gamac) (3.20.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /.venv/lib/python3.12/site-packages (from datasets==3.6.0->Gamac) (0.3.8)
Requirement already satisfied: pandas in /.venv/lib/python3.12/site-packages (from datasets==3.6.0->Gamac) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in /.venv/lib/python3.12/site-packages (from datasets==3.6.0->Gamac) (2.32.5)
Requirement already satisfied: xxhash in /.venv/lib/python3.12/site-packages (from datasets==3.6.0->Gamac) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /.venv/lib/python3.12/site-packages (from datasets==3.6.0->Gamac) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /.venv/lib/python3.12/site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->Gamac) (2025.3.0)
Requirement already satisfied: click>=8.0 in /.venv/lib/python3.12/site-packages (from distributed==2024.12.1->Gamac) (8.3.0)
Requirement already satisfied: cloudpickle>=3.0.0 in /.venv/lib/python3.12/site-packages (from distributed==2024.12.1->Gamac) (3.1.1)
Requirement already satisfied: dask==2024.12.1 in /.venv/lib/python3.12/site-packages (from distributed==2024.12.1->Gamac) (2024.12.1)
Requirement already satisfied: locket>=1.0.0 in /.venv/lib/python3.12/site-packages (from distributed==2024.12.1->Gamac) (1.0.0)
Requirement already satisfied: msgpack>=1.0.2 in /.venv/lib/python3.12/site-packages (from distributed==2024.12.1->Gamac) (1.1.2)
Requirement already satisfied: sortedcontainers>=2.0.5 in /.venv/lib/python3.12/site-packages (from distributed==2024.12.1->Gamac) (2.4.0)
Requirement already satisfied: tblib>=1.6.0 in /.venv/lib/python3.12/site-packages (from distributed==2024.12.1->Gamac) (3.1.0)
Requirement already satisfied: toolz>=0.11.2 in /.venv/lib/python3.12/site-packages (from distributed==2024.12.1->Gamac) (1.0.0)
Requirement already satisfied: tornado>=6.2.0 in /.venv/lib/python3.12/site-packages (from distributed==2024.12.1->Gamac) (6.5.2)
Requirement already satisfied: urllib3>=1.26.5 in /.venv/lib/python3.12/site-packages (from distributed==2024.12.1->Gamac) (2.5.0)
Requirement already satisfied: zict>=3.0.0 in /.venv/lib/python3.12/site-packages (from distributed==2024.12.1->Gamac) (3.0.0)
Requirement already satisfied: rapids-dask-dependency==25.2.* in /.venv/lib/python3.12/site-packages (from distributed-ucxx-cu12==0.42.0->Gamac) (25.2.0)
Requirement already satisfied: ucxx-cu12==0.42.* in /.venv/lib/python3.12/site-packages (from distributed-ucxx-cu12==0.42.0->Gamac) (0.42.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /.venv/lib/python3.12/site-packages (from huggingface-hub==0.24.6->Gamac) (4.15.0)
Requirement already satisfied: MarkupSafe>=2.0 in /.venv/lib/python3.12/site-packages (from Jinja2==3.1.4->Gamac) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /.venv/lib/python3.12/site-packages (from matplotlib==3.9.2->Gamac) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /.venv/lib/python3.12/site-packages (from matplotlib==3.9.2->Gamac) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /.venv/lib/python3.12/site-packages (from matplotlib==3.9.2->Gamac) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /.venv/lib/python3.12/site-packages (from matplotlib==3.9.2->Gamac) (1.4.9)
Requirement already satisfied: pyparsing>=2.3.1 in /.venv/lib/python3.12/site-packages (from matplotlib==3.9.2->Gamac) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /.venv/lib/python3.12/site-packages (from matplotlib==3.9.2->Gamac) (2.9.0.post0)
Requirement already satisfied: traitlets in /.venv/lib/python3.12/site-packages (from matplotlib-inline==0.1.7->Gamac) (5.14.3)
Requirement already satisfied: alembic>=1.5.0 in /.venv/lib/python3.12/site-packages (from optuna==4.3.0->Gamac) (1.17.0)
Requirement already satisfied: colorlog in /.venv/lib/python3.12/site-packages (from optuna==4.3.0->Gamac) (6.9.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /.venv/lib/python3.12/site-packages (from scikit-learn==1.5.1->Gamac) (3.6.0)
Requirement already satisfied: greenlet>=1 in /.venv/lib/python3.12/site-packages (from SQLAlchemy==2.0.40->Gamac) (3.2.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /.venv/lib/python3.12/site-packages (from sympy==1.13.3->Gamac) (1.3.0)
Requirement already satisfied: setuptools in /.venv/lib/python3.12/site-packages (from torch==2.7.0+cu128->Gamac) (80.9.0)
Requirement already satisfied: networkx in /.venv/lib/python3.12/site-packages (from torch==2.7.0+cu128->Gamac) (3.5)
Requirement already satisfied: nvidia-cufile-cu12==1.13.0.11 in /.venv/lib/python3.12/site-packages (from torch==2.7.0+cu128->Gamac) (1.13.0.11)
Requirement already satisfied: triton==3.3.0 in /.venv/lib/python3.12/site-packages (from torch==2.7.0+cu128->Gamac) (3.3.0)
Requirement already satisfied: regex!=2019.12.17 in /.venv/lib/python3.12/site-packages (from transformers==4.44.2->Gamac) (2025.9.18)
Requirement already satisfied: pynndescent>=0.5 in /.venv/lib/python3.12/site-packages (from umap-learn==0.5.7->Gamac) (0.5.13)
Requirement already satisfied: partd>=1.4.0 in /.venv/lib/python3.12/site-packages (from dask==2024.12.1->distributed==2024.12.1->Gamac) (1.4.2)
Requirement already satisfied: rmm-cu12==25.2.* in /.venv/lib/python3.12/site-packages (from pylibraft-cu12==25.2.*->cuvs-cu12==25.2.1->Gamac) (25.2.0)
Requirement already satisfied: dask-expr==1.1.21 in /.venv/lib/python3.12/site-packages (from rapids-dask-dependency==25.2.*->distributed-ucxx-cu12==0.42.0->Gamac) (1.1.21)
Requirement already satisfied: pynvml<13.0.0a0,>=12.0.0 in /.venv/lib/python3.12/site-packages (from ucxx-cu12==0.42.*->distributed-ucxx-cu12==0.42.0->Gamac) (12.0.0)
Requirement already satisfied: iniconfig>=1 in /.venv/lib/python3.12/site-packages (from pytest>=8.3.5->Gamac) (2.1.0)
Requirement already satisfied: pluggy<2,>=1.5 in /.venv/lib/python3.12/site-packages (from pytest>=8.3.5->Gamac) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /.venv/lib/python3.12/site-packages (from pytest>=8.3.5->Gamac) (2.19.2)
Requirement already satisfied: Mako in /.venv/lib/python3.12/site-packages (from alembic>=1.5.0->optuna==4.3.0->Gamac) (1.3.10)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /.venv/lib/python3.12/site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->Gamac) (3.13.0)
Requirement already satisfied: pytz>=2020.1 in /.venv/lib/python3.12/site-packages (from pandas->datasets==3.6.0->Gamac) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /.venv/lib/python3.12/site-packages (from pandas->datasets==3.6.0->Gamac) (2025.2)
Requirement already satisfied: six>=1.5 in /.venv/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib==3.9.2->Gamac) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /.venv/lib/python3.12/site-packages (from requests>=2.32.2->datasets==3.6.0->Gamac) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /.venv/lib/python3.12/site-packages (from requests>=2.32.2->datasets==3.6.0->Gamac) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /.venv/lib/python3.12/site-packages (from requests>=2.32.2->datasets==3.6.0->Gamac) (2025.10.5)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->Gamac) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->Gamac) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->Gamac) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->Gamac) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->Gamac) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->Gamac) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->Gamac) (1.22.0)
Downloading https://test-files.pythonhosted.org/packages/f3/64/a985e1bc2128e9a71035bba0a1a936c6bbe96d93647ecb61d596774edfe1/gamac-1.0.2-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 6.4 MB/s eta 0:00:0000:0100:01
Installing collected packages: Gamac
Successfully installed Gamac-1.0.2

In [6]:
import os
import sys

import numpy as np
import pandas as pd
from PIL import Image

from gamac import autoclustering
from gamac import estimation

In [7]:
import os
from minio import Minio
os.environ["SSL_CERT_FILE"] = 'all-data/public.crt'
def download_data_without_creds(data):
    client = Minio(
    '94.124.179.195:9000',
    secure=True
    )
    data = client.fget_object(
        'datasets',
        f'data/{data}',
        f'all-data/{data}'
    )
download_data_without_creds('synthetic_logs_1kk.csv')
# Импортируем датафрейм
data = pd.read_csv('all-data/synthetic_logs_1kk.csv', na_values=['missing'])
data['timestamp'] = pd.to_datetime(data['timestamp'], errors='coerce')
data.head(5)

,Unnamed: 0,object,agent,subject,environment,source,result,result code,tag,log level,label,traceback,protocol,action,property,timestamp
0,0,NaN,NaN,thread,NaN,24.149.203.18,[<:subject:> <:source:>] File does not exist:<...,NaN,NaN,error,NaN,event interval expired,NaN,NaN,lifetime 05:00,2025-04-18 10:08:58
1,1,dfs.FSNamesystem,ocsp.digicert.com:80,out block blk 8855628190418004805,NaN,transfer block blk -1132082380757283113 to 10....,<:action:>* NameSystem.addStoredBlock: blockMa...,NaN,27052.0,WARN,NaN,Redundant addStoredBlock request received for ...,NaN,Access denied,power/control problem,2025-03-28 10:08:58
2,2,spoolsv.exe *64,news.17173.com:80,thread,NaN,transfer block blk -1009207079038502874 to 10....,link errors remain current,NaN,6708.0,-1,state_change.unavailable,Redundant addStoredBlock request received for ...,NaN,NaN,power/control problem,2025-04-19 10:08:58
3,3,chrome.exe,pubads.g.doubleclick.net:443,node-139,NaN,84.92.64.33,"<:action:>, <:NUM:> bytes <:*:> <:*:> sent, <:...",NaN,NaN,NaN,NaN,timed,NaN,close,power/control problem,2025-04-14 10:08:58
4,4,partition,mini.cpc.sogou.com:80,thread,NaN,85.64.10.104,critical,NaN,385417.0,-1,status,must start with /,NaN,NaN,power/control problem,2025-04-16 10:08:58

In [8]:
gamac = autoclustering.Gamac(iter_limit=100, target_measures={estimation.internal.Internal.BR})

result = gamac.run(table=data)

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.71G [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/316 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/905 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/389 [00:00<?, ?B/s]

/.venv/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

=== MEASURES 1.1157617568969727s, {'BR': -16.44806280726097} ===
=== MEASURES 0.009341955184936523s, {'BR': -14.626955715340738} ===
=== ALGO 2.3537065982818604s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 2, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== ALGO 2.0265579223632812e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.33740411433523265, 'max_iter': 5, 'tol': 0.0001} ===
=== ALGO 34.414361000061035s, FailedRun, {'name': 'DBSCAN', 'eps': 1.0504753027357927, 'eps_sq': 1.1034983616578553, 'min_samples': 12} ===
=== ALGO 63.111104011535645s, FailedRun, {'name': 'HDBSCAN', 'min_cluster_size': 5, 'min_samples': 5} ===
=== MEASURES 0.01004934310913086s, {'BR': -11.692344446095483} ===
=== ALGO 135.4413707256317s, SuccessRun, {'name': 'Birch', 'threshold': 0.749319266971823, 'branching_factor': 22, 'n_clusters': 14} ===
=== MEASURES 0.00537872314453125s, {'BR': -13.687040946218175} ===
=== ALGO 0.05107903480529785s, SuccessRun, {'name': 'KMeans', 'n_clusters': 3, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.006258964538574219s, {'BR': -13.137139840028079} ===
=== ALGO 0.10951662063598633s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 4, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== ALGO 2.002716064453125e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.7609185200577301, 'max_iter': 5, 'tol': 0.0001} ===
=== ALGO 35.01362061500549s, FailedRun, {'name': 'DBSCAN', 'eps': 0.5581879588948837, 'eps_sq': 0.3115737974552364, 'min_samples': 10} ===
=== ALGO 161.99994945526123s, FailedRun, {'name': 'HDBSCAN', 'min_cluster_size': 7, 'min_samples': 10} ===
=== MEASURES 0.01745128631591797s, {'BR': -12.410450241379962} ===
=== ALGO 308.5242269039154s, SuccessRun, {'name': 'Birch', 'threshold': 0.25890253374704186, 'branching_factor': 45, 'n_clusters': 9} ===
=== MEASURES 0.016794204711914062s, {'BR': -11.33326226131598} ===
=== ALGO 0.1331648826599121s, SuccessRun, {'name': 'KMeans', 'n_clusters': 9, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.024093151092529297s, {'BR': -10.594481873935763} ===
=== ALGO 2.833641529083252s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 14, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== ALGO 2.1219253540039062e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.3238431770275632, 'max_iter': 5, 'tol': 0.0001} ===
=== ALGO 46.38256502151489s, FailedRun, {'name': 'DBSCAN', 'eps': 0.6148853856987614, 'eps_sq': 0.3780840375459146, 'min_samples': 13} ===
=== ALGO 210.13739132881165s, FailedRun, {'name': 'HDBSCAN', 'min_cluster_size': 10, 'min_samples': 13} ===
=== MEASURES 0.016605138778686523s, {'BR': -12.053524229999358} ===
=== ALGO 159.0463409423828s, SuccessRun, {'name': 'Birch', 'threshold': 0.26242275198341036, 'branching_factor': 16, 'n_clusters': 14} ===
=== MEASURES 0.014123678207397461s, {'BR': -13.739066047802956} ===
=== ALGO 0.07951784133911133s, SuccessRun, {'name': 'KMeans', 'n_clusters': 3, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.02327108383178711s, {'BR': -11.966442349688501} ===
=== ALGO 0.14925789833068848s, SuccessRun, {'name': 'KMeans', 'n_clusters': 8, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.0236968994140625s, {'BR': -10.70038923673593} ===
=== ALGO 2.2885866165161133s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 12, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.011684656143188477s, {'BR': -13.710997046504852} ===
=== ALGO 0.07125663757324219s, SuccessRun, {'name': 'KMeans', 'n_clusters': 3, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.023079872131347656s, {'BR': -11.842324526011616} ===
=== ALGO 0.14407587051391602s, SuccessRun, {'name': 'KMeans', 'n_clusters': 8, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.022807598114013672s, {'BR': -11.148160884352931} ===
=== ALGO 0.16138839721679688s, SuccessRun, {'name': 'KMeans', 'n_clusters': 10, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.019681930541992188s, {'BR': -10.904983437589499} ===
=== ALGO 0.1529252529144287s, SuccessRun, {'name': 'KMeans', 'n_clusters': 10, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.0202944278717041s, {'BR': -11.157608800049601} ===
=== ALGO 0.15674543380737305s, SuccessRun, {'name': 'KMeans', 'n_clusters': 10, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.019765138626098633s, {'BR': -10.87220943861992} ===
=== ALGO 1.9984300136566162s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 13, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.0067479610443115234s, {'BR': -14.626955715340738} ===
=== ALGO 0.04139852523803711s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 2, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.017353057861328125s, {'BR': -11.84076192470379} ===
=== ALGO 0.11314582824707031s, SuccessRun, {'name': 'KMeans', 'n_clusters': 7, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.010999202728271484s, {'BR': -13.68064375592568} ===
=== ALGO 0.07146191596984863s, SuccessRun, {'name': 'KMeans', 'n_clusters': 3, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.019225597381591797s, {'BR': -10.83626416719092} ===
=== ALGO 0.16182446479797363s, SuccessRun, {'name': 'KMeans', 'n_clusters': 11, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.02044057846069336s, {'BR': -11.124214630459226} ===
=== ALGO 372.65147852897644s, SuccessRun, {'name': 'Birch', 'threshold': 0.7972230965596586, 'branching_factor': 65, 'n_clusters': 12} ===
=== MEASURES 0.02636408805847168s, {'BR': -10.069647922081316} ===
=== ALGO 0.2168583869934082s, SuccessRun, {'name': 'KMeans', 'n_clusters': 15, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.01834249496459961s, {'BR': -12.039374369841935} ===
=== ALGO 0.12438178062438965s, SuccessRun, {'name': 'KMeans', 'n_clusters': 7, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.01595783233642578s, {'BR': -13.832469364882789} ===
=== ALGO 326.2113347053528s, SuccessRun, {'name': 'Birch', 'threshold': 0.7145352481530356, 'branching_factor': 52, 'n_clusters': 3} ===
=== MEASURES 0.021499156951904297s, {'BR': -11.863218493990502} ===
=== ALGO 0.7910139560699463s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 8, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.02656078338623047s, {'BR': -10.546645035737702} ===
=== ALGO 3.5360968112945557s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 15, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.025350570678710938s, {'BR': -10.160023524903464} ===
=== ALGO 0.20131587982177734s, SuccessRun, {'name': 'KMeans', 'n_clusters': 14, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.018102645874023438s, {'BR': -12.531569836815976} ===
=== ALGO 0.10648226737976074s, SuccessRun, {'name': 'KMeans', 'n_clusters': 5, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.020252227783203125s, {'BR': -12.203212870314829} ===
=== ALGO 0.113494873046875s, SuccessRun, {'name': 'KMeans', 'n_clusters': 6, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.028856754302978516s, {'BR': -10.593537352559988} ===
=== ALGO 3.0848817825317383s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 15, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== ALGO 175.46695232391357s, FailedRun, {'name': 'HDBSCAN', 'min_cluster_size': 10, 'min_samples': 10} ===
=== MEASURES 0.024837493896484375s, {'BR': -10.292905574564882} ===
=== ALGO 0.18323755264282227s, SuccessRun, {'name': 'KMeans', 'n_clusters': 14, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.017578840255737305s, {'BR': -12.23948019731142} ===
=== ALGO 0.37507104873657227s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 6, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== ALGO 45.67461276054382s, FailedRun, {'name': 'DBSCAN', 'eps': 0.052621817013945874, 'eps_sq': 0.0027690556258492035, 'min_samples': 12} ===
=== MEASURES 0.025058746337890625s, {'BR': -10.02062375465139} ===
=== ALGO 0.19358158111572266s, SuccessRun, {'name': 'KMeans', 'n_clusters': 15, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.021012067794799805s, {'BR': -11.874171317965242} ===
=== ALGO 0.8276283740997314s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 9, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== ALGO 45.57674789428711s, FailedRun, {'name': 'DBSCAN', 'eps': 0.5889084435960796, 'eps_sq': 0.3468131549387569, 'min_samples': 12} ===
=== MEASURES 0.023281574249267578s, {'BR': -11.095609294500623} ===
=== ALGO 1.4702482223510742s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 11, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.012893438339233398s, {'BR': -14.626955715340738} ===
=== ALGO 0.04158496856689453s, SuccessRun, {'name': 'KMeans', 'n_clusters': 2, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== ALGO 45.17725110054016s, FailedRun, {'name': 'DBSCAN', 'eps': 0.08774490129334767, 'eps_sq': 0.007699167702979325, 'min_samples': 6} ===
=== ALGO 48.16034817695618s, FailedRun, {'name': 'DBSCAN', 'eps': 1.0774814187862989, 'eps_sq': 1.1609662078297356, 'min_samples': 14} ===
=== MEASURES 0.021129131317138672s, {'BR': -12.651347494381408} ===
=== ALGO 0.5096855163574219s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 7, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.02250528335571289s, {'BR': -10.96904530826192} ===
=== ALGO 1.235607624053955s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 11, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.024411439895629883s, {'BR': -10.572592568517713} ===
=== ALGO 1.9848449230194092s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 14, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.016593456268310547s, {'BR': -12.892974105047216} ===
=== ALGO 0.34998106956481934s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 6, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.01997232437133789s, {'BR': -10.942123754065653} ===
=== ALGO 0.14598512649536133s, SuccessRun, {'name': 'KMeans', 'n_clusters': 10, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.021490812301635742s, {'BR': -10.891303137843792} ===
=== ALGO 2.033081531524658s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 13, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== ALGO 48.251869678497314s, FailedRun, {'name': 'DBSCAN', 'eps': 0.2512460605179262, 'eps_sq': 0.06312458292577743, 'min_samples': 6} ===
=== MEASURES 0.01833939552307129s, {'BR': -11.88284450641569} ===
=== ALGO 0.7263000011444092s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 8, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.015529394149780273s, {'BR': -13.137139840028079} ===
=== ALGO 0.1708519458770752s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 4, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== ALGO 1.6927719116210938e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.9823589766425284, 'max_iter': 5, 'tol': 0.0001} ===
=== MEASURES 0.023380279541015625s, {'BR': -10.594481873935763} ===
=== ALGO 2.471419095993042s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 14, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.027857065200805664s, {'BR': -9.941881725323737} ===
=== ALGO 0.20830082893371582s, SuccessRun, {'name': 'KMeans', 'n_clusters': 15, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.017498254776000977s, {'BR': -12.339828142231044} ===
=== ALGO 0.2422165870666504s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 5, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.020450592041015625s, {'BR': -10.968096716506121} ===
=== ALGO 1.2571351528167725s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 11, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.02446770668029785s, {'BR': -10.240520370638258} ===
=== ALGO 0.1853041648864746s, SuccessRun, {'name': 'KMeans', 'n_clusters': 14, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.018659591674804688s, {'BR': -11.996433781525743} ===
=== ALGO 0.9437704086303711s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 9, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.011589765548706055s, {'BR': -14.626955715340738} ===
=== ALGO 0.03706860542297363s, SuccessRun, {'name': 'KMeans', 'n_clusters': 2, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.010550498962402344s, {'BR': -14.561175073164007} ===
=== ALGO 386.87916445732117s, SuccessRun, {'name': 'Birch', 'threshold': 0.2703050342625214, 'branching_factor': 68, 'n_clusters': 2} ===
=== MEASURES 0.022466659545898438s, {'BR': -12.751695439301033} ===
=== ALGO 0.500434398651123s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 6, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.017879486083984375s, {'BR': -13.63555887892942} ===
=== ALGO 0.12618660926818848s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 3, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.03096485137939453s, {'BR': -10.208505669695473} ===
=== ALGO 0.21947836875915527s, SuccessRun, {'name': 'KMeans', 'n_clusters': 13, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.02250218391418457s, {'BR': -11.781714389142879} ===
=== ALGO 0.16037631034851074s, SuccessRun, {'name': 'KMeans', 'n_clusters': 8, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.03033280372619629s, {'BR': -10.477561390674577} ===
=== ALGO 3.9401705265045166s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 15, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.01933765411376953s, {'BR': -12.72857851941152} ===
=== ALGO 0.3782775402069092s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 5, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== MEASURES 0.023906469345092773s, {'BR': -12.516870888727047} ===
=== ALGO 0.11263132095336914s, SuccessRun, {'name': 'KMeans', 'n_clusters': 5, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.019995450973510742s, {'BR': -12.37155078346463} ===
=== ALGO 0.11890530586242676s, SuccessRun, {'name': 'KMeans', 'n_clusters': 6, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.01828289031982422s, {'BR': -13.70166978149816} ===
=== ALGO 0.09984040260314941s, SuccessRun, {'name': 'KMeans', 'n_clusters': 3, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== ALGO 82.76010131835938s, FailedRun, {'name': 'DBSCAN', 'eps': 1.3374923671326218, 'eps_sq': 1.7888858321380239, 'min_samples': 9} ===
=== MEASURES 0.029242992401123047s, {'BR': -10.813326554165432} ===
=== ALGO 1.9632666110992432s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 12, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.024822473526000977s, {'BR': -11.924012219876898} ===
=== ALGO 0.9544868469238281s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 8, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== ALGO 2.2411346435546875e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.5816186818892455, 'max_iter': 5, 'tol': 0.0001} ===
=== ALGO 1.33514404296875e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.5065578175318901, 'max_iter': 5, 'tol': 0.0001} ===
=== MEASURES 0.023583650588989258s, {'BR': -12.336601710361569} ===
=== ALGO 0.8840320110321045s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 8, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.02924633026123047s, {'BR': -10.442593354415965} ===
=== ALGO 0.2101902961730957s, SuccessRun, {'name': 'KMeans', 'n_clusters': 12, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.03506875038146973s, {'BR': -9.890588180393689} ===
=== ALGO 0.2585442066192627s, SuccessRun, {'name': 'KMeans', 'n_clusters': 15, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.016135215759277344s, {'BR': -14.626955715340738} ===
=== ALGO 0.06680417060852051s, SuccessRun, {'name': 'KMeans', 'n_clusters': 2, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.01886439323425293s, {'BR': -13.021845178077701} ===
=== ALGO 0.1111750602722168s, SuccessRun, {'name': 'KMeans', 'n_clusters': 4, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.02016758918762207s, {'BR': -13.137139840028079} ===
=== ALGO 0.2389233112335205s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 4, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.035366058349609375s, {'BR': -10.582810437187208} ===
=== ALGO 0.2256760597229004s, SuccessRun, {'name': 'KMeans', 'n_clusters': 14, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.02292776107788086s, {'BR': -12.039871336814635} ===
=== ALGO 0.13988304138183594s, SuccessRun, {'name': 'KMeans', 'n_clusters': 7, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== ALGO 2.002716064453125e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.5623368851215346, 'max_iter': 5, 'tol': 0.0001} ===
=== MEASURES 0.019402027130126953s, {'BR': -13.703402779869348} ===
=== ALGO 0.09709429740905762s, SuccessRun, {'name': 'KMeans', 'n_clusters': 3, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.02672743797302246s, {'BR': -11.526364930916964} ===
=== ALGO 0.15750932693481445s, SuccessRun, {'name': 'KMeans', 'n_clusters': 9, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.02471470832824707s, {'BR': -11.8632184939905} ===
=== ALGO 0.9213366508483887s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 8, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===
=== ALGO 2.5272369384765625e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.896021826030288, 'max_iter': 5, 'tol': 0.0001} ===
=== ALGO 298.85428762435913s, FailedRun, {'name': 'HDBSCAN', 'min_cluster_size': 7, 'min_samples': 13} ===
=== ALGO 81.91970300674438s, FailedRun, {'name': 'DBSCAN', 'eps': 1.3003966755215113, 'eps_sq': 1.6910315137073988, 'min_samples': 5} ===
=== MEASURES 0.019321203231811523s, {'BR': -14.626955715340738} ===
=== ALGO 0.08455157279968262s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 2, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== MEASURES 0.026901721954345703s, {'BR': -12.1130580444761} ===
=== ALGO 0.9060888290405273s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 7, 'max_iter': 20, 'init': 'random', 'tol': 0.0001} ===

In [9]:
# Получение топ-50 меток по лучшему классификатору
print(result.labels[:50])

[ 2 14  9  6  9 14 14 13  0  4  5  9 12  1  3  4  9  3  3  6 13  1  9  4
  7 14 14  0  2  3 13  1  6  7  3  1  9 14  4  9  3  7  3  7  8  1  3  9
 14  4]

In [10]:
# Импортируем картинки
images = []

# Получаем список файлов в директории
for filename in os.listdir('../../data/images/'):
    if 'png' not in filename:
        continue
    file_path = os.path.join('../../data/images/', filename)

    # Пытаемся открыть файл как изображение
    with Image.open(file_path) as img:
        images.append(img.copy())

images[:5]

[<PIL.Image.Image image mode=RGBA size=600x600>,
 <PIL.Image.Image image mode=RGBA size=651x888>,
 <PIL.Image.Image image mode=RGBA size=3433x4606>,
 <PIL.Image.Image image mode=RGBA size=114x102>,
 <PIL.Image.Image image mode=RGBA size=744x1052>]

In [11]:
gamac = Gamac(iter_limit=30)
empty_texts = ['' for i in range(len(images))]

result = gamac.run(image=images, text=empty_texts)

/.venv/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

=== Started CVI prediction ===
=== CVI prediction iteration 1/2 ====
=== CVI prediction iteration 2/2 ====
=== Picked SYM in 13.202826023101807s ===
=== MEASURES 0.3189883232116699s, {'SYM': 0.000511937877054524} ===
=== ALGO 2.4685208797454834s, FailedRun, {'name': 'BisectingKMeans', 'n_clusters': 12, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== ALGO 2.1696090698242188e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.7076722791579713, 'max_iter': 5, 'tol': 0.0001} ===
=== MEASURES 0.3281221389770508s, {'SYM': 0.0} ===
=== ALGO 2.0018069744110107s, SuccessRun, {'name': 'DBSCAN', 'eps': 1.309090159370299, 'eps_sq': 1.713717045360155, 'min_samples': 14} ===
=== ALGO 0.5287821292877197s, FailedRun, {'name': 'HDBSCAN', 'min_cluster_size': 9, 'min_samples': 8} ===
=== ALGO 4.424066066741943s, FailedRun, {'name': 'Birch', 'threshold': 0.4485855606022975, 'branching_factor': 66, 'n_clusters': 13} ===
=== MEASURES 0.1943802833557129s, {'SYM': 0.013563322590189343} ===
=== ALGO 0.2900238037109375s, SuccessRun, {'name': 'KMeans', 'n_clusters': 5, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.18327069282531738s, {'SYM': 0.010395605885474044} ===
=== ALGO 0.575833797454834s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 5, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== ALGO 2.5987625122070312e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.37062219068256674, 'max_iter': 5, 'tol': 0.0001} ===
=== ALGO 0.6336078643798828s, FailedRun, {'name': 'DBSCAN', 'eps': 0.316326733886323, 'eps_sq': 0.1000626025711886, 'min_samples': 6} ===
=== ALGO 4.085498571395874s, FailedRun, {'name': 'HDBSCAN', 'min_cluster_size': 14, 'min_samples': 15} ===
=== MEASURES 0.3299582004547119s, {'SYM': 0.02119713706353663} ===
=== ALGO 1.3101470470428467s, SuccessRun, {'name': 'Birch', 'threshold': 0.8101741749373312, 'branching_factor': 53, 'n_clusters': 14} ===
=== MEASURES 0.32622456550598145s, {'SYM': 0.002727079466052756} ===
=== ALGO 0.37277722358703613s, SuccessRun, {'name': 'KMeans', 'n_clusters': 2, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.2555727958679199s, {'SYM': 0.005240265211042903} ===
=== ALGO 0.3989841938018799s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 3, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== ALGO 2.4080276489257812e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.650427184182131, 'max_iter': 5, 'tol': 0.0001} ===
=== ALGO 0.6402654647827148s, FailedRun, {'name': 'DBSCAN', 'eps': 0.49505673512309895, 'eps_sq': 0.24508117099074214, 'min_samples': 9} ===
=== ALGO 3.102649688720703s, FailedRun, {'name': 'HDBSCAN', 'min_cluster_size': 11, 'min_samples': 11} ===
=== MEASURES 0.28665733337402344s, {'SYM': 0.020995963852497863} ===
=== ALGO 4.470674514770508s, SuccessRun, {'name': 'Birch', 'threshold': 0.610298735772977, 'branching_factor': 70, 'n_clusters': 7} ===
=== MEASURES 0.16588330268859863s, {'SYM': 0.016194671168658196} ===
=== ALGO 0.29267168045043945s, SuccessRun, {'name': 'KMeans', 'n_clusters': 7, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.2483196258544922s, {'SYM': 0.004594553123969863} ===
=== ALGO 0.4227776527404785s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 3, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== ALGO 2.5987625122070312e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.09485570459628681, 'max_iter': 5, 'tol': 0.0001} ===
=== MEASURES 0.33524298667907715s, {'SYM': 0.002639756974616493} ===
=== ALGO 0.3816032409667969s, SuccessRun, {'name': 'KMeans', 'n_clusters': 2, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== ALGO 0.1668863296508789s, FailedRun, {'name': 'KMeans', 'n_clusters': 15, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== MEASURES 0.19681859016418457s, {'SYM': 0.02425872370085239} ===
=== ALGO 0.31141233444213867s, SuccessRun, {'name': 'KMeans', 'n_clusters': 7, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== ALGO 2.1696090698242188e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.8731159976571748, 'max_iter': 5, 'tol': 0.0001} ===
=== MEASURES 0.1709747314453125s, {'SYM': 0.009581391702857059} ===
=== ALGO 0.50238037109375s, SuccessRun, {'name': 'BisectingKMeans', 'n_clusters': 5, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== ALGO 1.906193733215332s, FailedRun, {'name': 'BisectingKMeans', 'n_clusters': 14, 'max_iter': 20, 'init': 'k-means++', 'tol': 0.0001} ===
=== ALGO 1.8835067749023438e-05s, FailedRun, {'name': 'MeanShift', 'bandwidth': 0.6954590168019006, 'max_iter': 5, 'tol': 0.0001} ===
=== MEASURES 0.15224742889404297s, {'SYM': 0.023249431585059547} ===
=== ALGO 0.2904548645019531s, SuccessRun, {'name': 'KMeans', 'n_clusters': 8, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===
=== ALGO 0.5543584823608398s, FailedRun, {'name': 'HDBSCAN', 'min_cluster_size': 15, 'min_samples': 11} ===
=== MEASURES 0.1792895793914795s, {'SYM': 0.035428130012324005} ===
=== ALGO 0.27164125442504883s, SuccessRun, {'name': 'KMeans', 'n_clusters': 7, 'max_iter': 15, 'tol': 0.0001, 'random_state': None} ===

In [12]:
# Метки по датасету
print(result.labels)

[4 3 5 3 0 5 3 3 3 4 3 3 6 2 3 3 3 2 5 3 4 4 3 5 4 3 3 4 4 4 4 4 4 6 0 3 3
 3 2 0 3 5 6 4 2 2 5 5 5 4 3 2 2 2 3 6 4 0 3 4 2 3 6 3 6 4 3 0 3 5 6 6 2 3
 4 2 0 4 3 3 5 6 3 3 3 6 3 3 3 6 3 3 5 3 3 2 4 3 2 4 3 4 5 4 6 5 3 4 5 6 5
 4 3 3 3 3 5 3 3 3 6 6 2 3 4 5 3 6 3 2 4 4 0 3 6 3 6 4 6 4 5 5 6 6 4 3 6 0
 3 3 5 3 2 4 0 1 3 3 3 3 3 3 3 3 2 2 3 3 4 4 4 6 3 6 2 2 5 6 2 0 4 4 3 2 6
 3 5 3 3 4 2 0 3 0 3 6 3 5 0 3 0 4 3 5 3 2 6 4 3 6 3 0 2 3 3 4 6 3 5 5 5 2
 0 3 3 0 3 3 4 6 4 2 3 6 2 6 6 3 0 3 3 3 3 6 3 5 2 4 3 4 3 3 6 3 4 6 0 3 2
 3 3 2 3 3 2 0 3 3 2 6 3 3 3 2 5 2 6 3 4 2 6 6 6 2 6 2 4 2 3 4 0 6 2 6 3 5
 0 3 3 2 3 6 4 3 2 0 6 6 5 2 6 0 4 3 3 5 0 3 0 4 6 3 6 6 6 3 3 6 6 0 4 4 6
 0 3 2 4 6 5 3 6 2 5 6 2 6 4 2 3 3 0 6 3 2 4 2 2 3 3 6 6 3 2 3 3 2 2 4 5 5
 4 0 2 5 3 2 2 3 2 6 3 0 3 6 3 0 3 0 0 6 4 6 3 3 5 4 3 3 3 2 3 4 3 6 2 4 3
 0 0 5 2 5 3 4 5 3 0 6 3 0 3 2 5 2 4 6 5 2 3 4 2 2 2 3 2 4 0 5 3 6 2 4 2 6
 4 0 2 3 3 2 5 6 2 0 6 6 6 5 3 5 3 5 2 3 3 5 5 2 4 4 5 4 3 4 3 6 6 3 0 6 4
 3 6 6 3 3 3 3 0 0 3 4 3 0 6 5 3 3 6 5 4]